baseURL = 'https://package-papers.github.io/'
languageCode = 'en-us'
title = 'Packaged-Papers'
theme = 'Hugo-Theme'

pygmentsCodeFences = true
pygmentsUseClasses = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[[params.sidebar.menu]]
  name = "CONTENT"
  header = true
[[params.sidebar.menu]]
  name = "Posts"
  url = "/posts"